name: iOS Build and Test

on:
  push:
    branches:
      - develop

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache CocoaPods dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/Library/Caches/CocoaPods
            Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('Podfile.lock') }}
          restore-keys: ${{ runner.os }}-pods-

      - name: Clean Build Artifacts
        run: |
          rm -rf ~/Library/Developer/Xcode/DerivedData/*
          rm -rf ~/Library/Developer/Xcode/iOS\ DeviceSupport/*
          rm -rf ~/Library/Developer/Xcode/Archives/*

      - name: Remove Unused Simulators
        run: |
          xcrun simctl delete unavailable

      - name: Install CocoaPods
        run: brew install cocoapods

      - name: Install dependencies
        run: pod install

      - name: Build for iOS Simulator
        run: |
          xcodebuild clean build \
            -workspace TaskManagement.xcworkspace \
            -scheme TaskManagement \
            -sdk iphonesimulator \
            -configuration Debug \
            -destination 'platform=iOS Simulator,OS=17.0,name=iPhone 15 Pro Max' \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            PROVISIONING_PROFILE_SPECIFIER=""
            INDEX_WHILE_BUILDING=NO

      - name: Run Unit Tests on iOS Simulator
        run: |
          xcodebuild clean test \
            -workspace TaskManagement.xcworkspace \
            -scheme TaskManagement \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,OS=17.0,name=iPhone 15 Pro Max' | xcpretty

      # Add a step for UI tests if needed