name: iOS Build and Test

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: macos-latest

    steps:
      # Check out the repository
      - uses: actions/checkout@v2

      # Clean Derived Data and Cache
      - name: Clean Derived Data and Cache
        run: |
          rm -rf ~/Library/Developer/Xcode/DerivedData/*
          rm -rf ~/Library/Developer/Xcode/iOS\ DeviceSupport/*
          rm -rf ~/Library/Developer/Xcode/Archives/*

      # Remove Unused Simulators
      - name: Remove Unused Simulators
        run: |
          xcrun simctl delete unavailable

      - name: Install CocoaPods
        run: brew install cocoapods

      - name: Install dependencies
        run: pod install

      # Build the project
      - name: Build for iOS Simulator
        run: |
          xcodebuild clean build \
            -workspace TaskManagement.xcworkspace \
            -scheme TaskManagement \
            -sdk iphonesimulator \
            -configuration Debug \
            -destination 'platform=iOS Simulator,name=iPhone 15 Pro Max' \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            PROVISIONING_PROFILE_SPECIFIER=""

      # Run tests
      - name: Run Unit Tests on iOS Simulator
        run: |
          xcodebuild clean test \
            -workspace TaskManagement.xcworkspace \
            -scheme TaskManagement \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15 Pro Max'
